---
title: "Events Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Events in Michigan by Candidate

```{r}
events <- readRDS("events_saved.rds")

michigan<-events %>% 
  filter(state == "MI") %>% 
    group_by(cand_lastname) %>% 
    count(cand_lastname)



#Data Visualisation
fig <- plot_ly(data=michigan, labels = ~cand_lastname, values = ~n)

fig <- fig %>% add_pie(hole = 0.6) #would make a pie chart, to make a donut chart add the hole

fig <- fig %>% layout(
                  title = "Events in Michigan by Candidate",  showlegend = F,
                  xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                  yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

